# Site settings.
baseurl: http://natemow.github.io
title: natemow
description: This README was initially created more or less as a programming and design sandbox, resume and sometimes-blog for a person called &quot;Nate Mow&quot;.
author: Nate Mow
defaults:
  -
    scope:
      pages: "" # Denotes all pages.
      type: "pages"
    values:
      layout: default
  -
    scope:
      pages: "" # Denotes all pages.
      type: "posts"
    values:
      layout: default
  -
    scope:
      pages: "" # Denotes all pages.
      type: "drafts"
    values:
      layout: default

# Handling reading.
exclude: [ nbproject, vendor, script, assets/sass, assets/img/sprites/, assets/img/template/, Gemfile, Gemfile.lock, config.rb, README.md ]

# Conversion.
markdown: kramdown
permalink: pretty
