# Site settings.
baseurl: http://natemow.github.io
title: natemow
description: This README was initially created more or less as a programming and design sandbox, resume and sometimes-blog for a person called &quot;Nate Mow&quot;.
author: Nate Mow
defaults:
  -
    scope:
      pages: "" # Denotes all pages.
    values:
      layout: default

# Build settings.
exclude: [vendor]
markdown: kramdown
permalink: pretty
