# Site settings.
title: natemow
description: natemow
author: Nate Mow
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default

# Build settings.
markdown: kramdown
permalink: pretty
