# Site settings.
baseurl: http://natemow.github.io
title: natemow
description: This README was initially created more or less as a programming sandbox, resume and sometimes-blog for a person called &quot;Nate Mow&quot;.
author: (aka &quot;Nate Mow&quot;)
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default

# Build settings.
markdown: kramdown
permalink: pretty
